inherit_gem:
  sgcop: ruby/rubocop.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'db/*'
    - 'config/**/*'
  TargetRubyVersion: 2.4

# allow redirect_to xxx and return
Style/AndOr:
  EnforcedStyle: conditionals

# allow no document public class
Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# scope use ->{}
Style/Lambda:
  Enabled: false

# 1_000_000
Style/NumericLiterals:
  MinDigits: 7


# allow has_ and is_
Naming/PredicateName:
  NamePrefixBlacklist:
    - have_
    - is_
  NamePrefix:
    - have_
    - is_

Style/StringLiterals:
  Enabled: false

Metrics/MethodLength:
  Max: 15
  Exclude:
    - "db/migrate/*.rb"

Metrics/LineLength:
  Max: 120
  Exclude:
    - "db/migrate/*.rb"

Metrics/ClassLength:
  Enabled: false
